
name: Raft Test
# run go test under src/raft when push to github
on: 
  watch:
    types: started

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.18.3

      - name: Checkout Private Source Repository
        uses: actions/checkout@v3
        with:
          repository: endless-hu/6.824
          token: ${{ secrets.GH_PAT }}
          path: my_repo
      
      - name: Checkout This Repository
        uses: actions/checkout@v3
        with:
          path: this_repo

      - name: "Run Raft Tests"
        # plugin my private source code into the original repository, also copy the test script
        run: |
          git clone git://g.csail.mit.edu/6.824-golabs-2022 6.824
          cd 6.824/src
          cp $GITHUB_WORKSPACE/this_repo/scripts/go.mod .
          cd raft
          cp $GITHUB_WORKSPACE/my_repo/src/raft/raft.go .
          cp $GITHUB_WORKSPACE/this_repo/scripts/test-many_lab2.sh ./test-many.sh
          bash test-many.sh 2 20
