name: Test the workflow_dispacth

on: 
  workflow_dispatch:
  push:
  watch:
    types: started

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Hello World"
