name: Frangipani Test
# Will be triggered when I push to my private repo
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.18.3

      - name: Checkout Private Source Repository
        # Get the private source code from the private repository.
        uses: actions/checkout@v3
        with:
          repository: endless-hu/6.824
          token: ${{ secrets.GH_PAT }}
          path: my_repo
      
      - name: Checkout This Repository
        uses: actions/checkout@v3
        with:
          path: this_repo

      - name: "Run Frangipani Tests"
        run: |
          cd my_repo/src/frangipani
          ls
          for i in {1..30}; do 
            if ! go test -timeout 10m; then
              echo "Some tests fail!" && exit 1
            fi
            echo "============== Round $i Done ================"
          done
          echo
          echo "--------------------------------------------"
          echo "    Run Speed Test With Full Performance"
          sed '97d' client.go -i
          go test -run Speed

          git --no-pager log > $GITHUB_WORKSPACE/this_repo/src_commit_log.txt

      - name: Copy frangipani Out
        run: |
          cd $GITHUB_WORKSPACE/this_repo/frangipani
          ls
          cp $GITHUB_WORKSPACE/my_repo/src/frangipani/client.go .
          cp $GITHUB_WORKSPACE/my_repo/src/frangipani/common.go .
          cp $GITHUB_WORKSPACE/my_repo/src/frangipani/config.go .
          cp $GITHUB_WORKSPACE/my_repo/src/frangipani/lock_manager.go .
          cp $GITHUB_WORKSPACE/my_repo/src/frangipani/server.go .
          cp $GITHUB_WORKSPACE/my_repo/src/frangipani/test_test.go .

      - name: Auto Update
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Zhijing Hu
          author_email: qq906555703@gmail.com
          cwd: ./this_repo/
          message: "Auto Update"