name: MapReduce Test
# run tests against MapReduce when push to github
on: 
  push:
    branches:
      - main
  watch:
    types: started

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.18.3

      - name: Download Offial Repository
        run: git clone git://g.csail.mit.edu/6.824-golabs-2022 6.824
      
      - name: Checkout Private Source Repository
        uses: actions/checkout@v3
        with:
          repository: endless-hu/6.824
          token: ${{ secrets.GH_PAT }}
          path: my_repo

      - name: "Run MapReduce Tests"
        # plugin my private source code into the original repository,
        run: |
          cd $GITHUB_WORKSPACE/6.824/src
          cp -r $GITHUB_WORKSPACE/my_repo/src/mr/ ./mr
          cd main
          bash test-mr-many.sh 100