name: ShardKV Test
# Will be triggered when I push to my private repo
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.18.3

      - name: Checkout Private Source Repository
        # Get the private source code from the private repository.
        uses: actions/checkout@v3
        with:
          repository: endless-hu/6.824
          token: ${{ secrets.GH_PAT }}
          path: my_repo
      
      - name: Checkout This Repository
        # Get the test script from this public repository.
        uses: actions/checkout@v3
        with:
          path: this_repo

      - name: "Run ShardKV Tests"
        # plugin my private source code into the original repository, also copy the test script
        run: |
          git clone git://g.csail.mit.edu/6.824-golabs-2022 6.824
          cd 6.824/src
          cp $GITHUB_WORKSPACE/this_repo/scripts/go.mod .
          cd raft
          cp $GITHUB_WORKSPACE/my_repo/src/raft/raft.go .
          cd ../shardctrler
          cp $GITHUB_WORKSPACE/my_repo/src/shardctrler/client.go .
          cp $GITHUB_WORKSPACE/my_repo/src/shardctrler/server.go .
          cp $GITHUB_WORKSPACE/my_repo/src/shardctrler/common.go .
          cd ../shardkv
          cp $GITHUB_WORKSPACE/my_repo/src/shardkv/client.go .
          cp $GITHUB_WORKSPACE/my_repo/src/shardkv/server.go .
          cp $GITHUB_WORKSPACE/my_repo/src/shardkv/common.go .
          cp $GITHUB_WORKSPACE/my_repo/src/shardkv/util.go .
          
          cp $GITHUB_WORKSPACE/this_repo/scripts/test-many.sh ./test-many.sh
          bash test-many.sh Test 140
